### ISSUE TITLE
Unconditional mixins break other mods with custom waterloggable pressure plates

### ISSUE THREAD

**Issue by XFactHD** [TheMillman/WaterloggedRedstone#1]
Due to your mixins unconditionally applying to all instances of the blocks you are modifying, any mod trying to make their own waterloggable variant of such a block will crash on startup.

I received an issue report with this exact problem because I have custom pressure plates that are waterloggable: https://github.com/XFactHD/FramedBlocks/issues/193.

The easiest fix would be to guard the addition of the waterlogged property with a `this.getClass() == TheRespectiveVanillaBlock.class` check for the classes you expect the blocks to have in a vanilla environment. Any mod that doesn't add custom behaviour to their replica of the respective block would still be caught in that check and therefore modified as intended and any mod with a custom subclass would be left alone to avoid issues like this.

**Comment by TheMillman** [comment]
Thank you for reporting the error to me, I will try to fix it.

**Comment by TheMillman** [comment]
I just released an update of the mod on curseforge, I did several tests but I decided to completely remove both the pressure plates and the buttons, I think it's the best thing to avoid errors of this type, meanwhile there are mods like yours that do the same thing but a hundred times better.
I thank you again for everything.

**Comment by XFactHD** [comment]
Thank you for the quick response. The new version works fine with FramedBlocks in my tests as well 👍

**Comment by BlackAures1** [comment]
It's still a bit buggy with our mod

[crash-2022-11-30_05.56.00-fml.txt](https://github.com/TheMillman/WaterloggedRedstone/files/10118974/crash-2022-11-30_05.56.00-fml.txt)

**Comment by TheMillman** [comment]
I knew I had to fix it even in version 1.18.2, but lately I haven't been able to have time to work on my mods anymore. I'll fix it as soon as I can.
